version: '3'

services:
  client:
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /usr/src/app
    networks:
      - localnetwork

networks:
  localnetwork:
